name: crops_prediction
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_database: ^10.4.9
  syncfusion_flutter_gauges: ^25.1.42
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  flutter_staggered_animations: ^1.1.1
  animated_flip_counter: ^0.3.3
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
